### ISSUE TITLE
title and labels missing in d3heatmap()

### ISSUE THREAD

**Issue by Noor59007** [rstudio/d3heatmap#41] opened 2015-11-03 02:04 UTC
xlab ylab and title not displaying in d3heatmap()..

eg
    d3heatmap(avgs, show_grid = T, scale = "column", dendrogram = "none",anim_duration = 500, color = "Blues",k_col = c(.1,2),xlab="xaxisss",ylab="yaxis",title =paste("Comparison between ",input$ch1," and ",input$ch2))

**Comment by jcheng5** [comment] 2015-11-03 05:59
Dupe of #40

**Closed by jcheng5** 2015-11-03 05:59 UTC
